CREATE TABLE "match_prognosis" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"match_id" uuid NOT NULL,
	"model" text NOT NULL,
	"reasoning_effort" text,
	"run_at" timestamp with time zone NOT NULL,
	"xg_home" real NOT NULL,
	"xg_home_1t" real NOT NULL,
	"xg_home_2t" real NOT NULL,
	"xg_home_bands" jsonb NOT NULL,
	"resumo_home" text NOT NULL,
	"xg_away" real NOT NULL,
	"xg_away_1t" real NOT NULL,
	"xg_away_2t" real NOT NULL,
	"xg_away_bands" jsonb NOT NULL,
	"resumo_away" text NOT NULL,
	"total" real NOT NULL,
	"total_1t" real NOT NULL,
	"total_2t" real NOT NULL,
	"over25_prob" real NOT NULL,
	"btts_prob" real NOT NULL,
	"one_x_two" jsonb NOT NULL,
	"one_x_two_1t" jsonb NOT NULL,
	"one_x_two_2t" jsonb NOT NULL,
	"confianca" text NOT NULL,
	"resumo_geral" text NOT NULL,
	"drivers" jsonb NOT NULL,
	"reasoning" text,
	"prompt_text" text,
	"raw_output" jsonb,
	"reasoning_tokens" integer,
	"total_tokens" integer,
	"latency_ms" integer,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "match_prognosis_match_id_model_run_at_unique" UNIQUE("match_id","model","run_at")
);
--> statement-breakpoint
ALTER TABLE "match_prognosis" ADD CONSTRAINT "match_prognosis_match_id_match_id_fk" FOREIGN KEY ("match_id") REFERENCES "public"."match"("id") ON DELETE cascade ON UPDATE no action;