// Domain types come from the API contract (@workspace/api) — single source of truth.
export type {
  Absence,
  CardItem,
  CoachDetail,
  CoachMatch,
  Form,
  FormResult,
  GoalItem,
  GoalTimingBucket,
  League,
  LineupPlayer,
  Match,
  MatchGoalTiming,
  PlayerDetail,
  PlayerGoal,
  Round,
  Proportion,
  StandingRow,
  TeamAbsences,
  TeamGoalTiming,
  TeamLineup,
  TeamRef,
  TeamStanding,
  TeamTrends,
  TeamTrendSplit,
  VenueRecord,
} from "@workspace/api"
